# Plugins

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "@netlify/plugin-sitemap"

 [plugins.inputs]
 exclude = ['./404.html']

[[plugins]]
package = "netlify-plugin-submit-sitemap"

# Redirects

[[redirects]]
from = "/projects/canterburytheatreguild/avenueq/*"
to = "/canterbury-theatre-guild/avenue-q/:splat"

[[redirects]]
from = "/projects/canterburytheatreguild/steelmagnolias/*"
to = "/canterbury-theatre-guild/steel-magnolias/:splat"

[[redirects]]
from = "/projects/canterburytheatreguild/littlemermaid/*"
to = "/canterbury-theatre-guild/little-mermaid/:splat"

[[redirects]]
from = "/projects/canterburytheatreguild/9to5/*"
to = "/canterbury-theatre-guild/9-to-5/:splat"

[[redirects]]
from = "/projects/canterburytheatreguild/*"
to = "/canterbury-theatre-guild/:splat"

[[redirects]]
from = "/projects/guitardiy/*"
to = "/guitar-diy/:splat"

[[redirects]]
from = "/projects/sydneysecondarycollege/*"
to = "/sydney-secondary-college/:splat"

[[redirects]]
from = "/projects/volunteeringatgreenpeace/*"
to = "/volunteering-at-greenpeace/:splat"

[[redirects]]
from = "/projects/*"
to = "/:splat"
